### ISSUE TITLE
The bed raising mechanism on Gerald is prone to slipping.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#910]
There have been issues with the bed on Gerald going out of level. During the Laser maintenance day on Sunday 9th, we identified an issue with slackness in the main drive belt for the z-direction(bed raising and lowering) which is likely causing this issue.

It is very difficult to put sufficient tension in the belt with the current motor mount method (pushing the motor back as far as possible, then tightening 4 screws and bolts). It was suggested that it would be better to make a better tensioning pulley on the longer lengths of this belt, as the bed already has mounting holes for a belt tensioner. I would suggest also replacing the drive belt on the left side pulleys, as this is very tight, with a similar new belt and tensioner system, this will allow much easier bed levelling in the future.

This will need a degree of measurement and design, to be agreed by the laser maintenance team.

**Comment by DoESsean** [comment]
I assume this was fixed as Gerald is the main laser right now, but is that actually the case?

**Comment by magman2112** [comment]
No, this is still an issue. It is basically a poor design that will be included in the next major overhaul for Gerald. @Sean-anotherone and I have had a few idea’s about how to fix this, we just need to pick one then implement it. It will require some downtime though, hence waiting for overhaul time.

**Comment by magman2112** [comment]
Closing all issues related to Gerald as this machine is now out of commission and will hopefully find a new home soon.
